---
title: "EDA Project:Diamond Prices(Part 1)"
author: "RStudio"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(ggplot2)
library(dplyr)
```

```{r facebook}

data(diamonds)
str(diamonds
        )
```

## Plots


```{r plots} 

  ggplot(aes(x = price), data = diamonds) + 
  geom_histogram(binwidth = 1)

ggplot(aes(x = price), data = diamonds) + 
  geom_histogram(binwidth = 10, color = 'blue', fill = '#099DD9') +
  scale_x_continuous(breaks = seq(0,2000,100) , limits = c(0,2000))

ggplot(aes(x = price), data = diamonds) + 
  geom_histogram(binwidth = 10,color = 'black', fill = '#099DD9') +
  scale_x_continuous() +
  facet_wrap(~cut)

ggplot(aes(x = price), data = diamonds) + 
  geom_histogram(color = 'black', fill = '#099DD9') +
  scale_x_continuous() +
  facet_wrap(~cut , scales = "free_y")

ggplot(aes(x = price/carat), data = diamonds) + 
  geom_histogram(binwidth = 0.05,color = 'black', fill = '#099DD9') +
  scale_x_log10() +
  facet_wrap(~cut , scales = "free_y")

ggplot(aes(x = cut, y = price), data = subset(diamonds, !is.na(cut))) +
  geom_boxplot() + 
  coord_cartesian(ylim = c(0,7000))

ggplot(aes(x = clarity, y = price), data = subset(diamonds, !is.na(clarity))) +
  geom_boxplot() + 
  coord_cartesian(ylim = c(0,7000))

ggplot(aes(x = color, y = price), data = subset(diamonds, !is.na(color))) +
  geom_boxplot() + 
  coord_cartesian(ylim = c(0,8000))

ggplot(aes(x = color, y = price/carat), data = subset(diamonds, !is.na(color))) +
  geom_boxplot() + 
  coord_cartesian(ylim = c(0,6000))


ggplot(aes(x = carat) ,data = subset(diamonds)) +
  geom_freqpoly(aes(color = carat),binwidth = 0.1) + 
  scale_x_continuous(breaks = seq(0, 5, 0.2)) +
  scale_y_continuous(breaks = seq(0, 10000, 1000)) +
  xlab('Carat Size') + 
  ylab('Number of diamonds with that carat size')

```


